In [1]:
import pandas as pd
df = pd.read_csv("Hindi_clean.csv", encoding="utf-8")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_14500\1611541842.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_14500\1611541842.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_14500\1611541842.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\imaar\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_14500\1611541842.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\imaar\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [3]:
pd.set_option('display.max_colwidth', None)   # show full text
pd.set_option('display.max_rows', 100) 
df.head(30)

,text,label
0,"RT @ReshmaHindusta1: सुना है..?🤔\n\nटमाटर देशद्रोही हो गए है,\nमोड़ी जी की उम्र को पार कर गए हैं,""🤣",1
1,माफिया डॉन अतीक अहमद के बाहुबली छोटे भाई असरफ के साले जैद के आलिशान बंगले को मिटटी में मिला दिया \n\nबाबा जी के प्रकोप से कोई गुंडा मवाली नहीं बचने वाला https://t.co/WOjb0InNl5,1
2,#Watch : DRDO को बड़ी कामयाबी: देश ने रक्षा अनुसंधान के क्षेत्र में आज एक बड़ी कामयाबी हासिल करते हुए हाइपरसोनिक टेक्नॉलजी डेमोनस्ट्रेटर वीइकल (HSTDV) का सफल परीक्षण किया https://t.co/Dn7a7NG6Tk,0
3,"#Ballia युवक को दिनदहाड़े पत्नी के सामने गोली मारकर मौत के घाट उतारा, गोली चलने से इलाके में मचा हड़कंप, पुलिस ने शव पोस्टमार्टम के लिए भेजा, हल्दी थाने के जवाही दियार का मामला। @balliapolice @Uppolice #policemedianews",0
4,कोरोना महामारी के कारण 17 मई 2020 तक लॉकडाउन की वजह से मोबाइल कंपनियों नें सभी मोबाइल यूजर्स को फ्री इन्टरनेट देने का ऐलान किया है|,1
5,"पैंगोंग में भारत के एक्शन से चीन के उड़े होश, 24 घंटे में जारी किए 5 बयान \n https://t.co/KRLWFI0tSV via @NavbharatTimes \n\n#IndiaChinaFaceOff",0
6,ये दिन देखने से पहले मुझे मौत क्यों नही आ गई |क्या अब ये छोटे छोटे भाजपाई बच्चे भी राहुल सर को ज़लील करेंगे।\n\n,1
7,"जीडीपी में 2020-21 में 10% की आएगी गिरावट, जानिए क्या कह रहे हैं विशेषज्ञ\nhttps://t.co/PuavUYtD77 via @NavbharatTimes \n#GDP #Economy https://t.co/b6VtDr2Drb",0
8,"₹700 मिल रहा है सुनकर शाहीन बाग से भी कुछ महिलाएं बेगूसराय के लिए निकल रहे हैं। यहां तो सिर्फ ₹500 मिल रहा है। \nआपस में मिलकर एक रेट फिक्स कर लो, वरना छोटे-छोटे बच्चों को साथ लेकर महिलाएं कितना इधर-उधर करेंगे? उनके बारे में भी थोड़ा सोचो।",1
9,कमीनी औरत ये लेहरू नहीं है।ये चीन को और तेरे जैसे कमीनी को जहां से निकलीं है वहीं.... https://t.co/ZdDp7AXxzH,1
10,आरोप है कि एक फ्रॉड ने व्यक्ति से तीन बार वन टाइम पासवर्ड (ओटीपी) लिया और अकाउंट से 1.61 लाख गायब हो गए. \n\nhttps://t.co/nf5i0c5gWw,0
11,"""कंगना राणावत बाईसा भाजपा का प्रचार करेंगी बिहार में"" अब सब नाटक समझ आ ही गया होगा....? फिर भी क्या बिहार विधानसभा के आगामी आम चुनाव में भाजपा का एनङीऐ चुनाव हार गया तब भी मोदी और शाह कंगना रनौत को वाई श्रेणी की सुरक्षा यथावत बनाये रखेगी ??",1
12,यह असम के डिटेंशन सेंटर का कच्चा चिट्ठा है क्या हिंदू क्या मुसलमान क्या सिख इसाई सब को जेल में ठूंसा जाएगा\nजो लोग घर में आराम फरमा रहे हैं कल उनके बीवी बच्चे जेलों में सड़ रहे होंगे!\nhttp://Sc.st.obc व मुस्लिम भाई सभी एक हो जाओ,1
13,"मथुरा जेल से रिहा होते ही डॉ. कफील खान बोले- STF का शुक्रिया, जिन्होंने एनकाउंटर नहीं किया\n\nhttps://t.co/EWvoApnCUh",0
14,"देश भर के #JEE-#NEET के छात्रों को बिहार चुनाव में #भाजपा का बहिष्कार करने का एलान करना चाहिए,\n\nदेखिए फिर कैसे Exam स्थगित होता है\n\n#INDIAunitedtoPostponeJEE_NEET",1
15,@SonuSood अब हर कोई तो सोनू सुद जैसा नायक बन नहीं सकता ऐसी प्रतिभा ऐसी विलक्षण शक्ति ईश्वर कई सौ करोड़ों मनुष्य में किसी एक को देता है आप जैसा होना असम्भव नहीं परन्तु बहुत कठीन है एक देशी कहावत है सब कुतीया गया चली जायेंगी तो पत्तल कौन चाटेगा बस वही यहां की जनता भी है,1
16,फरीदाबाद पुलिस ने शहर के एक ओयो होटल में चल रहे कैसीनो का पर्दाफाश किया।\n#Faridabad \n\nhttps://t.co/Vy1FQZA3hG,0
17,"वीडियो: रूस में महिला के मुंह से निकाला गया सांप; गार्डन में सोते वक्त मुंह से पेट में घुस गया था 4 फीट का सांप, डॉक्टरों ने बेहोश कर ट्यूब की मदद से बाहर निकाला https://t.co/nnV7NiSWXM #Russia #Snake",0
18,"मैं मुंबई से नहीं हूं, लेकिन मैं 5-6 बार मुंबई गया हूं, #Mumbai भारत का सबसे सुंदर और सुरक्षित शहर है जहां एक लड़की या कोई भी व्यक्ति रात में भी सड़क पर सुरक्षित रूप से घूम सकता है। बेवकूफ 12 वीं फैल कंगना को मुंबई की तुलना POK से करने के लिए जेल में डालना चाहिए ...",1
19,"ब्रेकिंग न्यूज़- \n\nमहा नालायक हच्चन साहब ने कहा मैं कुछ नहीं बोलूँगा मेरे मुंह में बवासीर है, 😂😂😂",1
20,राष्ट्रपति #RamNathKovind ने पूर्व राष्ट्रपति #PranabMukherjee को दी श्रद्धांजलि\n\n#PranabDa https://t.co/xlWr0gVQgq,0
21,फ़्रांस की चार्ली हेब्दो ने फिर पैगंबर मोहम्मद का कार्टून छापा -मैग्जीन ने कहा हम नहीं झुकेगें,0
22,"बिहार: भारत का एकमात्र ऐसा किला जो जमीन पर नहीं, बल्कि जमीन के नीचे है, यहां पढ़ें अकल्पनीय जानकारी\n\nरंजन सिंह राजपूत की रिपोर्ट\n\nhttps://t.co/qexaEQokUy",0
23,#संजय_सिंह_गुंडा_है बंदर को बटेर।साले स्पैम मर थे गधों ने सांसद बना दिया,1
24,अब विदेशी छात्रों को देश की अलग अलग यूनिवर्सिटी में दाखिले के लिए अलग अलग फॉर्म भरने की जरूरत नही पड़ेगी.\n\nhttps://t.co/XvmUvWXdYv,0
25,@aamir_khan भारत में मच गई हाहाकार रोटी के लिए ताली बजा रहे हैं युवा भारत की हालात लीबिया सीरिया तालिबान से भी बदतर हालात https://t.co/L0i6fmwXvn,1
26,उत्तर प्रदेश की राजधानी लखनऊ में डबल मर्डर की ख़बर है. मुख्यमंत्री आवास के पास ये घटना हुई. हाई सिक्योरिटी ज़ोन वाले थाना गौतम पल्ली क्षेत्र की रेलवे कॉलोनी में एक रेलवे अधिकारी की पत्नी और उनके बेटे की गोली मार दी गई.\n\nhttps://t.co/2fp9y5a81d,0
27,"कोलकाता नाइट राइडर्स ने दो बार 2012 और 2014 में खिताब अपने नाम किया था, हालांकि इसके बाद वह पिछले छह सालों में फाइनल में भी नहीं पहुंच पाई है.\n#KKR #IPL2020 \nhttps://t.co/9VFI3pkI9q",0
28,शाहीन बाग की काले टेन्ट वाली शेरनियाँ😂 खैरात में मिले ₹500 लेने के लिए 🤗 क्योंकि रेट फिक्स है न ज्यादा न कम,1
29,"कई रहस्यों को अपने अंदर समेटे है बिहार के कैमूर में स्थित यह मंदिर, आज भी क्षेत्र में खुदाई के दौरान मिलती हैं मूर्तियां\n\nhttps://t.co/zoaSxvN8nW",0

In [4]:
def clean1(text):
    import re, html
    
    text = html.unescape(text)
    
    # remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    
    # remove mentions
    text = re.sub(r'@\w+', '', text)
    
    # remove RT
    text = re.sub(r'\bRT\b', '', text)
    
    # remove leading junk
    text = re.sub(r'^[:\-\s]+', '', text)
    
    # remove symbols like | ()
    text = re.sub(r'[|()]+', '', text)
    
    # remove ellipsis (...)
    text = re.sub(r'\.{2,}', ' ', text)
    
    # normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [5]:
df['text']= df['text'].apply(clean1)

In [6]:
df.head(30)

,text,label
0,"सुना है ?🤔 टमाटर देशद्रोही हो गए है, मोड़ी जी की उम्र को पार कर गए हैं,""🤣",1
1,माफिया डॉन अतीक अहमद के बाहुबली छोटे भाई असरफ के साले जैद के आलिशान बंगले को मिटटी में मिला दिया बाबा जी के प्रकोप से कोई गुंडा मवाली नहीं बचने वाला,1
2,#Watch : DRDO को बड़ी कामयाबी: देश ने रक्षा अनुसंधान के क्षेत्र में आज एक बड़ी कामयाबी हासिल करते हुए हाइपरसोनिक टेक्नॉलजी डेमोनस्ट्रेटर वीइकल HSTDV का सफल परीक्षण किया,0
3,"#Ballia युवक को दिनदहाड़े पत्नी के सामने गोली मारकर मौत के घाट उतारा, गोली चलने से इलाके में मचा हड़कंप, पुलिस ने शव पोस्टमार्टम के लिए भेजा, हल्दी थाने के जवाही दियार का मामला। #policemedianews",0
4,कोरोना महामारी के कारण 17 मई 2020 तक लॉकडाउन की वजह से मोबाइल कंपनियों नें सभी मोबाइल यूजर्स को फ्री इन्टरनेट देने का ऐलान किया है,1
5,"पैंगोंग में भारत के एक्शन से चीन के उड़े होश, 24 घंटे में जारी किए 5 बयान via #IndiaChinaFaceOff",0
6,ये दिन देखने से पहले मुझे मौत क्यों नही आ गई क्या अब ये छोटे छोटे भाजपाई बच्चे भी राहुल सर को ज़लील करेंगे।,1
7,"जीडीपी में 2020-21 में 10% की आएगी गिरावट, जानिए क्या कह रहे हैं विशेषज्ञ via #GDP #Economy",0
8,"₹700 मिल रहा है सुनकर शाहीन बाग से भी कुछ महिलाएं बेगूसराय के लिए निकल रहे हैं। यहां तो सिर्फ ₹500 मिल रहा है। आपस में मिलकर एक रेट फिक्स कर लो, वरना छोटे-छोटे बच्चों को साथ लेकर महिलाएं कितना इधर-उधर करेंगे? उनके बारे में भी थोड़ा सोचो।",1
9,कमीनी औरत ये लेहरू नहीं है।ये चीन को और तेरे जैसे कमीनी को जहां से निकलीं है वहीं,1
10,आरोप है कि एक फ्रॉड ने व्यक्ति से तीन बार वन टाइम पासवर्ड ओटीपी लिया और अकाउंट से 1.61 लाख गायब हो गए.,0
11,"""कंगना राणावत बाईसा भाजपा का प्रचार करेंगी बिहार में"" अब सब नाटक समझ आ ही गया होगा ? फिर भी क्या बिहार विधानसभा के आगामी आम चुनाव में भाजपा का एनङीऐ चुनाव हार गया तब भी मोदी और शाह कंगना रनौत को वाई श्रेणी की सुरक्षा यथावत बनाये रखेगी ??",1
12,यह असम के डिटेंशन सेंटर का कच्चा चिट्ठा है क्या हिंदू क्या मुसलमान क्या सिख इसाई सब को जेल में ठूंसा जाएगा जो लोग घर में आराम फरमा रहे हैं कल उनके बीवी बच्चे जेलों में सड़ रहे होंगे! व मुस्लिम भाई सभी एक हो जाओ,1
13,"मथुरा जेल से रिहा होते ही डॉ. कफील खान बोले- STF का शुक्रिया, जिन्होंने एनकाउंटर नहीं किया",0
14,"देश भर के #JEE-#NEET के छात्रों को बिहार चुनाव में #भाजपा का बहिष्कार करने का एलान करना चाहिए, देखिए फिर कैसे Exam स्थगित होता है #INDIAunitedtoPostponeJEE_NEET",1
15,अब हर कोई तो सोनू सुद जैसा नायक बन नहीं सकता ऐसी प्रतिभा ऐसी विलक्षण शक्ति ईश्वर कई सौ करोड़ों मनुष्य में किसी एक को देता है आप जैसा होना असम्भव नहीं परन्तु बहुत कठीन है एक देशी कहावत है सब कुतीया गया चली जायेंगी तो पत्तल कौन चाटेगा बस वही यहां की जनता भी है,1
16,फरीदाबाद पुलिस ने शहर के एक ओयो होटल में चल रहे कैसीनो का पर्दाफाश किया। #Faridabad,0
17,"वीडियो: रूस में महिला के मुंह से निकाला गया सांप; गार्डन में सोते वक्त मुंह से पेट में घुस गया था 4 फीट का सांप, डॉक्टरों ने बेहोश कर ट्यूब की मदद से बाहर निकाला #Russia #Snake",0
18,"मैं मुंबई से नहीं हूं, लेकिन मैं 5-6 बार मुंबई गया हूं, #Mumbai भारत का सबसे सुंदर और सुरक्षित शहर है जहां एक लड़की या कोई भी व्यक्ति रात में भी सड़क पर सुरक्षित रूप से घूम सकता है। बेवकूफ 12 वीं फैल कंगना को मुंबई की तुलना POK से करने के लिए जेल में डालना चाहिए",1
19,"ब्रेकिंग न्यूज़- महा नालायक हच्चन साहब ने कहा मैं कुछ नहीं बोलूँगा मेरे मुंह में बवासीर है, 😂😂😂",1
20,राष्ट्रपति #RamNathKovind ने पूर्व राष्ट्रपति #PranabMukherjee को दी श्रद्धांजलि #PranabDa,0
21,फ़्रांस की चार्ली हेब्दो ने फिर पैगंबर मोहम्मद का कार्टून छापा -मैग्जीन ने कहा हम नहीं झुकेगें,0
22,"बिहार: भारत का एकमात्र ऐसा किला जो जमीन पर नहीं, बल्कि जमीन के नीचे है, यहां पढ़ें अकल्पनीय जानकारी रंजन सिंह राजपूत की रिपोर्ट",0
23,#संजय_सिंह_गुंडा_है बंदर को बटेर।साले स्पैम मर थे गधों ने सांसद बना दिया,1
24,अब विदेशी छात्रों को देश की अलग अलग यूनिवर्सिटी में दाखिले के लिए अलग अलग फॉर्म भरने की जरूरत नही पड़ेगी.,0
25,भारत में मच गई हाहाकार रोटी के लिए ताली बजा रहे हैं युवा भारत की हालात लीबिया सीरिया तालिबान से भी बदतर हालात,1
26,उत्तर प्रदेश की राजधानी लखनऊ में डबल मर्डर की ख़बर है. मुख्यमंत्री आवास के पास ये घटना हुई. हाई सिक्योरिटी ज़ोन वाले थाना गौतम पल्ली क्षेत्र की रेलवे कॉलोनी में एक रेलवे अधिकारी की पत्नी और उनके बेटे की गोली मार दी गई.,0
27,"कोलकाता नाइट राइडर्स ने दो बार 2012 और 2014 में खिताब अपने नाम किया था, हालांकि इसके बाद वह पिछले छह सालों में फाइनल में भी नहीं पहुंच पाई है. #KKR #IPL2020",0
28,शाहीन बाग की काले टेन्ट वाली शेरनियाँ😂 खैरात में मिले ₹500 लेने के लिए 🤗 क्योंकि रेट फिक्स है न ज्यादा न कम,1
29,"कई रहस्यों को अपने अंदर समेटे है बिहार के कैमूर में स्थित यह मंदिर, आज भी क्षेत्र में खुदाई के दौरान मिलती हैं मूर्तियां",0

In [7]:
import re

def final_test_prep(text):
    if not isinstance(text, str): return ""
    
    # 1. Strip leading/trailing quotes and colons from CSV export
    text = text.strip('": ')
    
    # 2. Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    
    # 3. Strip '#' but keep the word
    text = re.sub(r'#(\w+)', r'\1', text)
    
    # 4. Remove extra whitespace and newlines
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['clean_text'] = df['text'].apply(final_test_prep)

In [10]:
df['label'].value_counts()

label
0    4358
1    3834
Name: count, dtype: int64

In [14]:
df=df.drop(columns ="text")

In [15]:
df.to_csv("cleaned_hindi_final.csv", index=False, encoding="utf-8-sig")

In [16]:
df.sample(10)

,label,clean_text
1153,0,कृपया अपने जनपद के जिलाधिकारी या सम्बंधित एसडीएम से शिकायत करें
1479,1,"विकास खोजने वो चले, विकास मिला न कहीं। अगर वो सोचते देश की, विकास ढूंढते यहीं।।"
54,1,गांधी खानदान विदेश में अपना इलाज करा कर साबित कर दिया कि एक भी HOSPITAL का निर्माण इस देश नहीं कराया.🤔👍
6143,0,"अठावले ने कहा कि सिब्बल, आजाद और अन्य दिग्गज कांग्रेसी नेताओं पर भाजपा के साथ मिलीभगत का आरोप लगाया गया है, इसलिए उन्हें ज्योतिरादित्य सिंधिया की तरह अपना इस्तीफा देना चाहिए और भाजपा में शामिल हो जाना चाहिए।"
4042,1,देखना साहब एक दिन मोर को भी बेच देंगे और कहेगे सही से उड़ नहीं रहा था !🤣
7248,0,"दिल्ली मेट्रो: इतनी खाली? 7 सितंबर यानी आज से दिल्ली समेत कई शहरों में मेट्रो सेवाएं शुरू हुई हैं. दिल्ली मेट्रो में शुरुआती घंटों में ऐसी भीड़ रही. किस रूट पर कब चलेगी मेट्रो, क्या हैं नियम? पूरी स्टोरी:-"
3041,0,राशिफलः आज इन राशियों को व्यवसायिक योजना में मिलेगी सफलता horoscopes aajkarashifal
2893,1,केंद्र सरकार ने किसी भी सूरत में दिसंबर तक स्कूल न खोलने का फैसला लिया है।
34,1,"यदि कांग्रेस की डिक्शनरी में ""हिंदुत्व"" शब्द ही नहीं है तो हिंदुओं की डिक्शनरी में ""कांग्रेस"" शब्द क्यों है? जागो और मिटा दो😡 👎"
2807,0,"संजय निरुपम का राउत पर निशाना, कहा- कंगना पर बयान ‘शिवसेना की नीचता’"

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8192 entries, 0 to 8191
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       8192 non-null   int64
 1   clean_text  8192 non-null   object
dtypes: int64(1), object(1)
memory usage: 128.1+ KB