In [1]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_12508\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_12508\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_12508\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\imaar\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\imaar\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\imaar\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\imaar\AppData\Local\Temp\ipykernel_12508\4080736814.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\imaar\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\imaar\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\imaar\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [46]:
df = pd.read_csv("English_clean.csv")

In [47]:
df.head(20)

,text,label
0,!!! RT @mayasolovely: As a woman you shouldn't complain about cleaning up your house. &amp; as a man you should always take the trash out...,0
1,!!!!! RT @mleew17: boy dats cold...tyga dwn bad for cuffin dat hoe in the 1st place!!,1
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby4life: You ever fuck a bitch and she start to cry? You be confused as shit,1
3,!!!!!!!!! RT @C_G_Anderson: @viva_based she look like a tranny,1
4,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you hear about me might be true or it might be faker than the bitch who told it to ya &#57361;,1
5,"!!!!!!!!!!!!!!!!!!""@T_Madison_x: The shit just blows me..claim you so faithful and down for somebody but still fucking with hoes! &#128514;&#128514;&#128514;""",1
6,"!!!!!!""@__BrighterDays: I can not just sit up and HATE on another bitch .. I got too much shit going on!""",1
7,!!!!&#8220;@selfiequeenbri: cause I'm tired of you big bitches coming for us skinny girls!!&#8221;,1
8,""" &amp; you might not get ya bitch back &amp; thats that """,1
9,""" @rhythmixx_ :hobbies include: fighting Mariam""\n\nbitch",1
10,""" Keeks is a bitch she curves everyone "" lol I walked into a conversation like this. Smh",1
11,""" Murda Gang bitch its Gang Land """,1
12,""" So hoes that smoke are losers ? "" yea ... go on IG",1
13,""" bad bitches is the only thing that i like """,1
14,""" bitch get up off me """,1
15,""" bitch nigga miss me with it """,1
16,""" bitch plz whatever """,1
17,""" bitch who do you love """,1
18,""" bitches get cut off everyday B """,1
19,""" black bottle &amp; a bad bitch """,1

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    24783 non-null  object
 1   label   24783 non-null  int64
dtypes: int64(1), object(1)
memory usage: 387.4+ KB

In [49]:
df['label'].value_counts()

label
1    20620
0     4163
Name: count, dtype: int64

In [50]:
df.sample(10)

,text,label
3683,@Johnny3_ @HPGuilty trash ain't it,0
4188,@MrRedMartian this pic is trash. D!ck is dry af.,1
1130,"&#8220;@BasedChasen: Grandmas always b asking you ""Do you have a girlfriend???"" No....I got hoes tf you mean&#8221; real shit.",1
15794,RT @Jenna_Garcia13: &#8220;@OfficialVondell: #MyGirlfriendNotAllowedTo have milkshakes.. let that hoe bring one boy to the yard.. and watch what &#8230;,1
8178,Breezy gotta sleep this hoe,1
12896,Monkey see monkey doo,0
19390,RT @juliebenz: I drink unicorn tears... RT @thecarnage07: @juliebenz And they say blondes don't age well :) You look like you're 20 :) ho&#8230;,0
19039,RT @gemini_starr These hoes be acting up!,1
22272,Trust none bitch I don't wife a bitch? Bitch I won't,1
7129,@tayscalf must have run out of brownies,0

In [51]:
pd.set_option('display.max_colwidth', None)   # show full text
pd.set_option('display.max_rows', 100)        # increase rows shown

df.head(20)

,text,label
0,!!! RT @mayasolovely: As a woman you shouldn't complain about cleaning up your house. &amp; as a man you should always take the trash out...,0
1,!!!!! RT @mleew17: boy dats cold...tyga dwn bad for cuffin dat hoe in the 1st place!!,1
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby4life: You ever fuck a bitch and she start to cry? You be confused as shit,1
3,!!!!!!!!! RT @C_G_Anderson: @viva_based she look like a tranny,1
4,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you hear about me might be true or it might be faker than the bitch who told it to ya &#57361;,1
5,"!!!!!!!!!!!!!!!!!!""@T_Madison_x: The shit just blows me..claim you so faithful and down for somebody but still fucking with hoes! &#128514;&#128514;&#128514;""",1
6,"!!!!!!""@__BrighterDays: I can not just sit up and HATE on another bitch .. I got too much shit going on!""",1
7,!!!!&#8220;@selfiequeenbri: cause I'm tired of you big bitches coming for us skinny girls!!&#8221;,1
8,""" &amp; you might not get ya bitch back &amp; thats that """,1
9,""" @rhythmixx_ :hobbies include: fighting Mariam""\n\nbitch",1
10,""" Keeks is a bitch she curves everyone "" lol I walked into a conversation like this. Smh",1
11,""" Murda Gang bitch its Gang Land """,1
12,""" So hoes that smoke are losers ? "" yea ... go on IG",1
13,""" bad bitches is the only thing that i like """,1
14,""" bitch get up off me """,1
15,""" bitch nigga miss me with it """,1
16,""" bitch plz whatever """,1
17,""" bitch who do you love """,1
18,""" bitches get cut off everyday B """,1
19,""" black bottle &amp; a bad bitch """,1

In [60]:
import re
import html

def clean_english_final(text):
    text = html.unescape(text)
    
    # remove RT + mentions
    text = re.sub(r'\bRT\b', '', text)
    text = re.sub(r'@\w+', '', text)
    
    # remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    
    # reduce repeated punctuation
    text = re.sub(r'!{2,}', '!', text)
    text = re.sub(r'\?{2,}', '?', text)
    
    # remove leading junk (!!!, :, spaces)
    text = re.sub(r'^[:\-\s!]+', '', text)
    
    # remove ellipsis
    text = re.sub(r'\.{2,}', ' ', text)
    
    # remove quotes (normal + fancy)
    text = re.sub(r'["“”‘’]', '', text)
    
    # normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [77]:
df['clean_text'] = df['clean_text'].apply(clean_english_final)

In [78]:
import pandas as pd
import re

def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    # 1. Remove leading/trailing special characters (!!!!, quotes, colons, spaces)
    # This regex looks at the start (^) and end ($) of the string
    text = re.sub(r'^[!:\s"\'“”]+', '', text) 
    text = re.sub(r'[!:\s"\'“”]+$', '', text)

    # 2. Reduce multiple exclamation/question marks to a single one
    # This keeps the 'intent' but removes the noise
    text = re.sub(r'!+', '!', text)
    text = re.sub(r'\?+', '?', text)

    # 3. Remove extra whitespace
    text = " ".join(text.split())

    return text

# Assuming your dataframe is named 'df'
df['clean_text'] = df['clean_text'].apply(preprocess_text)

# Preview results
print(df['clean_text'].head(10))

0    As a woman you shouldn't complain about cleaning up your house. & as a man you should always take the trash out
1                                                     boy dats cold tyga dwn bad for cuffin dat hoe in the 1st place
2                                        Dawg! : You ever fuck a bitch and she start to cry? You be confused as shit
3                                                                                             she look like a tranny
4                   The shit you hear about me might be true or it might be faker than the bitch who told it to ya 
5                The shit just blows me claim you so faithful and down for somebody but still fucking with hoes! 😂😂😂
6                                       I can not just sit up and HATE on another bitch I got too much shit going on
7                                                      cause I'm tired of you big bitches coming for us skinny girls
8                                                                     & you might not get ya bitch back & thats that
9                                                                             hobbies include: fighting Mariam bitch
Name: clean_text, dtype: object

In [79]:
import pandas as pd
import re

def advanced_clean(text):
    if not isinstance(text, str):
        return ""

    # 1. Remove the specific leading/trailing junk from your CSV export
    # This handles: "Initial quotes, !!!!, and leading spaces
    text = re.sub(r'^[!:\s"\'“]+', '', text)
    text = re.sub(r'[!:\s"\'”]+$', '', text)

    # 2. Fix the "double quote" artifacts inside the text
    # Often happens when CSVs export text containing quotes
    text = text.replace('""', '"')

    # 3. Strip the '#' from hashtags but keep the word
    text = re.sub(r'#(\w+)', r'\1', text)

    # 4. Remove URLs (Hate speech models don't need links)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 5. Handle repetition (Optional but recommended)
    # Reduces "LMAOOOOO" to "LMAOO" so the tokenizer doesn't get confused
    text = re.sub(r'(.)\1{3,}', r'\1\1', text)

    # 6. Final whitespace cleanup
    text = " ".join(text.split())
    
    return text


df['clean_text'] = df['clean_text'].apply(advanced_clean)

In [80]:
pd.set_option('display.max_colwidth', None)   # show full text
pd.set_option('display.max_rows', 100)        # increase rows shown

df.head(30)

,label,clean_text
0,0,As a woman you shouldn't complain about cleaning up your house. & as a man you should always take the trash out
1,1,boy dats cold tyga dwn bad for cuffin dat hoe in the 1st place
2,1,Dawg! : You ever fuck a bitch and she start to cry? You be confused as shit
3,1,she look like a tranny
4,1,The shit you hear about me might be true or it might be faker than the bitch who told it to ya 
5,1,The shit just blows me claim you so faithful and down for somebody but still fucking with hoes! 😂😂😂
6,1,I can not just sit up and HATE on another bitch I got too much shit going on
7,1,cause I'm tired of you big bitches coming for us skinny girls
8,1,& you might not get ya bitch back & thats that
9,1,hobbies include: fighting Mariam bitch
10,1,Keeks is a bitch she curves everyone lol I walked into a conversation like this. Smh
11,1,Murda Gang bitch its Gang Land
12,1,So hoes that smoke are losers ? yea go on IG
13,1,bad bitches is the only thing that i like
14,1,bitch get up off me
15,1,bitch nigga miss me with it
16,1,bitch plz whatever
17,1,bitch who do you love
18,1,bitches get cut off everyday B
19,1,black bottle & a bad bitch
20,1,broke bitch cant tell me nothing
21,1,cancel that bitch like Nino
22,1,cant you see these hoes wont change
23,1,fuck no that bitch dont even suck dick 😂😂😂 the Kermit videos bout to fuck IG up
24,1,got ya bitch tip toeing on my hardwood floors 😂
25,1,her pussy lips like Heaven doors 😌
26,1,hoe what its hitting for
27,1,i met that pussy on Ocean Dr . i gave that pussy a pill 😌
28,1,i need a trippy bitch who fuck on Hennessy
29,1,i spend my money how i want bitch its my business

In [81]:
df.to_csv("cleaned_final_english.csv", index=False, encoding="utf-8-sig")

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       24783 non-null  int64
 1   clean_text  24783 non-null  object
dtypes: int64(1), object(1)
memory usage: 387.4+ KB